### ISSUE TITLE
Have the problem to make extension

### ISSUE THREAD

**Issue by budarin** [RPG-18/pg_ulid#3]
I'm a newbie in linux and have the problem to make the extension on Debian

Could you provide a list of all needed dependencies and full cmake command, please

At now I have installed
- git
- make
- g++
- build-essential postgresql-server-dev-14

but still have some errors. the last :
```cmd
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Releas PostgreSQL_TYPE_INCLUDE_DIR=./usr/include/postgresql/
CMake Error: The source directory "/pg_ulid/PostgreSQL_TYPE_INCLUDE_DIR=./usr/include/postgresql" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```
I don't what to do with it

**Comment by RPG-18** [comment]
Hi. I'll see tomorrow.
